### ISSUE TITLE
Convert In-Memory Records from ArrayList to HashMap

### ISSUE THREAD

**Issue by sscalf-umgc** [umgc-smart-tool/smart-tool#21]
The ArrayList has served well up to this point, but utilizing a HashMap<ReferenceNumber, Record> will help with saving and updating.  It will also help prevent duplicate records as we can do a check for the reference number and perform an update.  The save() method could simply call the update() method or vice versa.

**Comment by sirhcsema** [comment]
Working on this now. I'll let you know if I have questions in discord
